import { useState } from "react";
import { getNotifications } from "../data";
import type { NotifItem } from "../data";
import { EmptyState, PageHeader, SectionLabel } from "../shared";
import { fmtDateTime } from "../../lib/adminStore";

export default function Notifications() {
  const [items, setItems] = useState<NotifItem[]>(getNotifications());

  const groups = {
    People: items.filter((n) => n.href === "/admin/volunteers"),
    Community: items.filter((n) => n.href === "/admin/concerns" || n.href === "/admin/questions"),
    Content: items.filter(
      (n) => n.href === "/admin/updates" || n.href === "/admin/media"
    ),
    Calendar: items.filter((n) => n.href === "/admin/activities"),
  };

  return (
    <>
      <PageHeader eyebrow="System" title="Notification center">
        <a className="abtn abtn--ghost" href="/admin">
          Back to overview
        </a>
      </PageHeader>

      {items.length === 0 ? (
        <EmptyState
          title="No notifications"
          detail="Notifications appear only for real activity: new volunteer registrations, concerns, questions, content awaiting review, media awaiting approval, and upcoming activities. When there is nothing pending, this stays empty."
        />
      ) : (
        <>
          <button
            className="abtn abtn--ghost"
            style={{ marginBottom: "0.6rem" }}
            onClick={() => {
              setItems([]);
            }}
          >
            Mark all as viewed
          </button>
          {(
            Object.keys(groups) as Array<keyof typeof groups>
          ).map((g) =>
            groups[g].length === 0 ? null : (
              <div key={g}>
                <SectionLabel>{g}</SectionLabel>
                <div className="astack">
                  {groups[g].map((n) => (
                    <a key={n.id} href={n.href} className="arow">
                      <div className="arow__main" style={{ gridTemplateColumns: "minmax(10rem,1fr) 8rem" }}>
                        <div>
                          <p className="arow__title">{n.label}</p>
                          <p className="arow__sub">{n.detail}</p>
                        </div>
                        <div style={{ textAlign: "right" }}>
                          <span className="amono">{n.at ? fmtDateTime(n.at) : ""}</span>
                        </div>
                      </div>
                    </a>
                  ))}
                </div>
              </div>
            )
          )}
        </>
      )}

      <SectionLabel>How notifications are derived</SectionLabel>
      <p className="amuted" style={{ fontSize: "0.82rem", lineHeight: 1.7 }}>
        Items are derived from pending real records (for example, a volunteer
        still in NEW status, or a question not yet answered). "Mark all as
        viewed" clears the list for this session; with a backend, seen-state
        becomes per-user and notification rows are generated by the server.
      </p>
    </>
  );
}